sudo: false
dist: xenial
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
env:
- DEBUG=1
python:
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - pip install tox-travis -r requirements-dev.txt
script:
  - tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
